<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QUE9GD3" failures="1" tests="3" name="testCases.LoginTest" time="31.650" errors="0" timestamp="2020-05-28T20:12:26 IST" skipped="2">
  <testcase classname="testCases.LoginTest" name="loginTest" time="0.497">
    <skipped/>
  </testcase> <!-- loginTest -->
  <system-out/>
  <testcase classname="testCases.LoginTest" name="loginTest" time="0.152">
    <skipped/>
  </testcase> <!-- loginTest -->
  <system-out/>
  <testcase classname="testCases.LoginTest" name="loginTest" time="31.001">
    <failure message="TestNG fail" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: TestNG fail
at org.testng.Assert.fail(Assert.java:97)
at com.HybridFramework.Keywords.GenericKeywords.reportFailure(GenericKeywords.java:175)
at com.HybridFramework.Keywords.GenericKeywords.getObject(GenericKeywords.java:158)
at com.HybridFramework.Keywords.AppKeywords.validateLogin(AppKeywords.java:53)
at com.HybridFramework.Drivers.DriverScript.executeKeywords(DriverScript.java:100)
at testCases.LoginTest.loginTest(LoginTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <system-out/>
</testsuite> <!-- testCases.LoginTest -->
